services:
  backend:
    build: .
    ports:
      - "59632:59632"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pomoflashdb
      DB_HOST: database
      DB_PORT: 5432
      EXPRESS_PORT: 59632
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pomoflashdb
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb.sql:/initdb.sql

volumes:
  postgres-data: